# Generated by Django 2.1.7 on 2019-12-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
