# Generated by Django 2.1.7 on 2019-12-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developen', '0003_auto_20191205_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='reward',
        ),
        migrations.AddField(
            model_name='project',
            name='eward',
            field=models.DecimalField(decimal_places=2, default='50.00', max_digits=6),
        ),
    ]
