# Generated by Django 2.1.7 on 2019-12-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developen', '0004_auto_20191205_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='eward',
            new_name='reward',
        ),
    ]
