# Generated by Django 2.1.7 on 2019-12-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developen', '0005_auto_20191205_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='default description', max_length=300),
        ),
        migrations.AddField(
            model_name='task',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.DecimalField(decimal_places=2, default='50.00', max_digits=6),
        ),
    ]
